# coding: utf-8

"""
    Watch and Chill

    This is a sample application for demonstrating CI/CD using GitOps and Kubernetes.  Some useful links:  * [The Pet Watch and Chill repository](https://github.com/lago-morph/chiller) * [Design document corresponding to this version of the API](https://github.com/lago-morph/chiller/wiki/Let's-Watch-design)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chiller_api_client
from chiller_api_client.models.movie_list import MovieList  # noqa: E501
from chiller_api_client.rest import ApiException


class TestMovieList(unittest.TestCase):
    """MovieList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMovieList(self):
        """Test MovieList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = chiller_api_client.models.movie_list.MovieList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
