# coding: utf-8

"""
    Watch and Chill

    This is a sample application for demonstrating CI/CD using GitOps and Kubernetes.  Some useful links:  * [The Pet Watch and Chill repository](https://github.com/lago-morph/chiller) * [Design document corresponding to this version of the API](https://github.com/lago-morph/chiller/wiki/Let's-Watch-design)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chiller_api_client
from chiller_api_client.api.user_api import UserApi  # noqa: E501
from chiller_api_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        Create a new user  # noqa: E501
        """
        pass

    def test_login_user(self):
        """Test case for login_user

        Log in as user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
