# coding: utf-8

"""
    Watch and Chill

    This is a sample application for demonstrating CI/CD using GitOps and Kubernetes.  Some useful links:  * [The Pet Watch and Chill repository](https://github.com/lago-morph/chiller) * [Design document corresponding to this version of the API](https://github.com/lago-morph/chiller/wiki/Let's-Watch-design)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chiller_api_client
from chiller_api_client.models.jwt import JWT  # noqa: E501
from chiller_api_client.rest import ApiException


class TestJWT(unittest.TestCase):
    """JWT unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJWT(self):
        """Test JWT"""
        # FIXME: construct object with mandatory attributes with example values
        # model = chiller_api_client.models.jwt.JWT()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
