# coding: utf-8

"""
    Watch and Chill

    This is a sample application for demonstrating CI/CD using GitOps and Kubernetes.  Some useful links:  * [The Pet Watch and Chill repository](https://github.com/lago-morph/chiller) * [Design document corresponding to this version of the API](https://github.com/lago-morph/chiller/wiki/Let's-Watch-design)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chiller_api_client
from chiller_api_client.api.movies_api import MoviesApi  # noqa: E501
from chiller_api_client.rest import ApiException


class TestMoviesApi(unittest.TestCase):
    """MoviesApi unit test stubs"""

    def setUp(self):
        self.api = MoviesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_movie(self):
        """Test case for add_movie

        Add a movie to user's list  # noqa: E501
        """
        pass

    def test_list_movies(self):
        """Test case for list_movies

        Get the list of movies for a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
