{
 "title": "Chiller application",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Response time through frontend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service, quantile) (chiller_frontend_gunicorn_request_duration{service=\"chiller-frontend\"})",
     "legendFormat": "quantile={{`{{quantile}}`}}"
    }
   ]
  },
  {
   "title": "Response time through API",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service, quantile) (chiller_api_gunicorn_request_duration{service=\"chiller-api\"})",
     "legendFormat": "quantile={{`{{quantile}}`}}"
    }
   ]
  },
  {
   "title": "Request rate through frontend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(service, status) (rate(chiller_frontend_http_response_code{component=\"frontend\"}[$__rate_interval]))",
     "legendFormat": "status={{`{{status}}`}}"
    }
   ]
  },
  {
   "title": "Request rate through API",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by(service, status) (rate(chiller_api_http_response_code{component=\"api\"}[$__rate_interval]))",
     "legendFormat": "status={{`{{status}}`}}"
    }
   ]
  },
  {
   "title": "DB fetch rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"chiller\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB insert rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"chiller\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}