{{ with .Values.dbSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
data:
  database: {{ .database | default (randAlpha 24) | b64enc }}
  password: {{ .password | default (randAlpha 24) | b64enc }}
  username: {{ .username | default (randAlpha 24) | b64enc }}
{{- end }}
