{{ range .Values.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  {{- if .replicaCount }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
{{ include "chiller.pod" . | indent 4 }}
...
{{ end }}
