# coding: utf-8

# flake8: noqa

"""
    Watch and Chill

    This is a sample application for demonstrating CI/CD using GitOps and Kubernetes.  Some useful links:  * [The Pet Watch and Chill repository](https://github.com/lago-morph/chiller) * [Design document corresponding to this version of the API](https://github.com/lago-morph/chiller/wiki/Let's-Watch-design)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from chiller_api_client.api.movies_api import MoviesApi
from chiller_api_client.api.user_api import UserApi
# import ApiClient
from chiller_api_client.api_client import ApiClient
from chiller_api_client.configuration import Configuration
# import models into sdk package
from chiller_api_client.models.jwt import JWT
from chiller_api_client.models.movie import Movie
from chiller_api_client.models.user import User
