[project]
name = "chiller_api"
version = "0.1.0"
dependencies = [
    "flask",
    "flask_testing == 0.8.1",
    "connexion[swagger-ui] >= 2.14, < 3.0",
    "pyjwt >= 2.7",
    "six",
    "psycopg >= 3.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
