name: main - Build and Test
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'release*'


jobs:
  build-packages:
    uses: ./.github/workflows/pkg_build.yml
  unit-test-chiller-frontend:
    uses: ./.github/workflows/frontend_test_unit.yml
    needs: build-packages
  unit-test-chiller-api:
    uses: ./.github/workflows/api_test_unit.yml
    needs: build-packages
  build-chiller-api-image:
    uses: ./.github/workflows/api_build_image.yml
    needs: unit-test-chiller-api
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
  build-chiller-frontend-image:
    uses: ./.github/workflows/frontend_build_image.yml
    needs: unit-test-chiller-frontend
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
  integration-test-chiller:
    uses: ./.github/workflows/chiller_test_integration.yml
    needs: [ build-chiller-api-image, unit-test-chiller-frontend ]
  browser-test-chiller:
    uses: ./.github/workflows/chiller_test_browser.yml
    needs: [ integration-test-chiller, build-chiller-frontend-image ]

