name: main - Build and Test
on: workflow_dispatch

jobs:
  build-packages:
    uses: ./.github/workflows/pkg_build.yml
  unit-test-chiller-frontend:
    uses: ./.github/workflows/frontend_test_unit.yml
    needs: build-packages
  unit-test-chiller-api:
    uses: ./.github/workflows/api_test_unit.yml
    needs: build-packages
  build-chiller-api-image:
    uses: ./.github/workflows/api_build_image.yml
    needs: unit-test-chiller-api
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

