# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Frontend test unit

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  frontend-test-unit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: update pip and install buildtools
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Build chiller_api_client package
      run: python -m build sdk
    - name: Build chiller_frontend package
      run: python -m build frontend
    - name: Install dependencies
      run: |
        python -m pip install pytest
        python -m pip install --find-links sdk/dist --find-links frontend/dist chiller_api_client chiller_frontend
    - name: Test with pytest
      run: |
        pytest frontend/tests
