# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Frontend test unit

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  frontend-test-unit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: update pip
      run: python -m pip install --upgrade pip
    - name: Build chiller_api_client package
      run: |
        python -m pip install build
        python -m build sdk
    - name: Install dependencies
      run: |
        python -m pip install pytest
        python -m pip install --find-links sdk/dist chiller_api_client
        if [ -f frontend/requirements.txt ]; then pip install -r frontend/requirements.txt; fi
        if [ -f frontend/test-requirements.txt ]; then pip install -r frontend/test-requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest frontend/tests
