name: sub - Frontend test unit

on: workflow_call

jobs:
  frontend-test-unit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: download built packages
      uses: actions/download-artifact@v4
      with:
        name: dist

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install -f sdk/dist chiller_api_client
        python -m pip install -f frontend/dist chiller_frontend

    - name: Test with pytest
      run: |
        pytest frontend/tests
