name: release - run release test
on: 
  workflow_dispatch: {}
  push:
    branches:
      - 'release-0.1.1'

jobs:
  get-recent-tag:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Check out repository code
        uses: actions/checkout@v4
      - id: get-tag
        name: Get the most recent tag in current branch
        run: |
          /bin/bash -c "git tag --sort=taggerdate --merged"
