name: test - detect if PR merged 
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - 'test-release-*'
    types: closed

# Kudos to https://stackoverflow.com/questions/59077079/how-to-get-pull-request-number-within-github-actions-workflow for info on how to do this.
env:
  GH_EVENT_NAME: ${{ github.event_name }}
  PR_ACTION: ${{ github.event.action }}
  PR_NUMBER: ${{ github.event.number }}
  PR_MERGED: ${{ github.event.pull_request.merged }}
  TO_PROCESS: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged }}

jobs:
  test-pr-merge-show:
    runs-on: ubuntu-latest
    steps:
      - id: print-my-action
        name: print out triggering action
        run: |
          echo "event name is: <$GH_EVENT_NAME>"
          echo "pr number is: <$PR_NUMBER>"
          echo "pr action is: <$PR_ACTION>"
          echo "pr merged is: <$PR_MERGED>"
  test-pipe-job:
    runs-on: ubuntu-latest
    steps:
      - id: test-pipe
        run: /bin/bash -c 'echo bob | sed -e "s/ob/OB/"'
  test-pr-process-job:
    # environment variables are not available in the jobs.if workflow key
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - id: compute-tag-name
        name: Compute tag name for merge
        run: | 
          BASEREF=${{ github.event.pull_request.base.ref }}
          echo $BASEREF
          DATE_TIME=$(date --utc +'%Y%m%d-%H%M%S')
          echo $DATE_TIME
          echo "${{ github.event.pull_request.base.ref }}-RC-$(date --utc +'%Y%m%d-%H%M%S')"
          /bin/bash -c 'echo ${{ github.event.pull_request.base.ref }}-RC-$(date --utc +"%Y%m%d-%H%M%S") | sed -e "s/^test-release-/v/"'
          /bin/bash -c 'echo ${{ github.event.pull_request.base.ref }}-RC-$(date --utc +"%Y%m%d-%H%M%S") | sed -e "s/^test-release-/new_tag=v/" >> "$GITHUB_ENV"'
      - id: show-tag-name
        name: Show the tag name for the merge
        run: echo "the tag to use is <$new_tag>"
