name: test - detect PR number and add comment
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - 'test-release*'

# Kudos to https://stackoverflow.com/questions/59077079/how-to-get-pull-request-number-within-github-actions-workflow for info on how to do this.
env:
  GH_EVENT_NAME: ${{ github.event_name }}
  PR_NUMBER: ${{ github.event.number }}
  PR_ACTION: ${{ github.event.action }}

jobs:
  test-pr-open:
    runs-on: ubuntu-latest
    steps:
      - id: print-my-action
        name: print out triggering action
        run: |
          echo "event name is: <$GH_EVENT_NAME>"
          echo "pr number is: <$PR_NUMBER>"
          echo "pr action is: <$PR_ACTION>"
  comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
#      - name: Checkout repository to get hash
#        uses: actions/checkout@v4
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
#          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: type=sha,format=long
#          labels: org.opencontainers.image.title=${{ env.IMAGE_NAME }}
      - id: print-output
        name: Debug print the tags
        run: echo ${{ steps.meta.outputs.tags }}
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ steps.meta.outputs.tags }}
            })
