name: test - detect PR number and add comment
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - 'test-release*'

# Kudos to https://stackoverflow.com/questions/59077079/how-to-get-pull-request-number-within-github-actions-workflow for info on how to do this.
env:
  GH_EVENT_NAME: ${{ github.event_name }}
  PR_NUMBER: ${{ github.event.number }}
  PR_ACTION: ${{ github.event.action }}

jobs:
  test-pr-open:
    runs-on: ubuntu-latest
    steps:
      - id: print-my-action
        name: print out triggering action
        run: |
          echo "event name is: <$GH_EVENT_NAME>"
          echo "pr number is: <$PR_NUMBER>"
          echo "pr action is: <$PR_ACTION>"
  comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - id: set-temp-tag-name
        name: Set the tag name used by the previous steps
        run: echo "temptag=$(date --utc)" >> $GITHUB_ENV
      - id: print-output
        name: Debug print the tags
        run: echo "the tag is $temptag"
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "tag used is: $temptag"
            })
